### ISSUE TITLE
ld: unrecognized option '--require-defined=...'

### ISSUE THREAD

**Issue by tbelaire** [tsgates/rust.ko#18]
Hi, I'm really excited about the newest patch, with bindgen support, but I'm getting errors when compiling it.

```
ld -m elf_x86_64   --gc-sections --entry=init_module --require-defined=cleanup_module  -r -o /home/tbelaire/Code/rust.ko/build/hello.o /home/tbelaire/Code/rust.ko/build/src/module.o /home/tbelaire/Code/rust.ko/build/libhello.a 
ld: unrecognized option '--require-defined=cleanup_module'

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
My binutils package is up to date, should I be using a llvm linker or something?

Oh, and I needed to add in 

     "-fno-delete-null-pointer-checks",

to the `CLANG_ARGS_BLACKLIST`, but that's fine.

**Comment by cuviper** [comment]
It appears `--require-defined` is a new option in binutils 2.26: [ld/NEWS](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=ld/NEWS;hb=refs/tags/binutils-2_26)

**Comment by tbelaire** [comment]
I don't know how to install the newer version of binutils.

```
sudo apt-get install binutils=2.26
```
fails.

Is there a way to not pass this flag?

**Comment by BlueT** [comment]
@tbelaire try my PR, it works on my Ubuntu 14.04.
